words = {
    # Природа (Nature)
    "сонце": "sun",
    "місяць": "moon",
    "зірка": "star",
    "небо": "sky",
    "вода": "water",
    "земля": "earth",
    "дерево": "tree",
    "ліс": "forest",
    "річка": "river",
    "озеро": "lake",
    "гора": "mountain",
    "квітка": "flower",
    "трава": "grass",
    "пісок": "sand",
    "океан": "ocean",
    "хмара": "cloud",
    "сніг": "snow",
    "дощ": "rain",
    "вітер": "wind",
    "пташка": "bird",

    # Людина (Human)
    "чоловік": "man",
    "жінка": "woman",
    "дитина": "child",
    "око": "eye",
    "вухо": "ear",
    "рука": "hand",
    "нога": "leg",
    "голова": "head",
    "серце": "heart",
    "мозок": "brain",
    "шкіра": "skin",
    "кров": "blood",
    "кістка": "bone",
    "зуб": "tooth",
    "волосся": "hair",
    "обличчя": "face",
    "посмішка": "smile",
    "голос": "voice",
    "тіло": "body",
    "душа": "soul",

    # Емоції (Emotions)
    "радість": "joy",
    "смуток": "sadness",
    "гнів": "anger",
    "страх": "fear",
    "любов": "love",
    "ненависть": "hatred",
    "подив": "surprise",
    "сором": "shame",
    "гордість": "pride",

    # Професії (Professions)
    "лікар": "doctor",
    "вчитель": "teacher",
    "інженер": "engineer",
    "кухар": "cook",
    "пілот": "pilot",
    "водій": "driver",
    "музикант": "musician",
    "поліцейський": "policeman",
    "фермер": "farmer",
    "програміст": "programmer",
    "механік": "mechanic",
    "адвокат": "lawyer",
    "архітектор": "architect",
    "перукар": "hairdresser",
    "журналіст": "journalist",
    "художник": "artist",
    "фотограф": "photographer",
    "офіціант": "waiter",
    "бухгалтер": "accountant",
    "секретар": "secretary",

    # Побутові предмети (Household Items)
    "стіл": "table",
    "стілець": "chair",
    "диван": "sofa",
    "ліжко": "bed",
    "лампа": "lamp",
    "вікно": "window",
    "двері": "door",
    "холодильник": "refrigerator",
    "плита": "stove",
    "чашка": "cup",
    "тарілка": "plate",
    "ложка": "spoon",
    "вилка": "fork",
    "ніж": "knife",
    "годинник": "clock",
    "килим": "carpet",
    "дзеркало": "mirror",
    "шафа": "wardrobe",
    "пральна машина": "washing machine",
    "телевізор": "television",

    # Їжа та напої (Food and Drinks)
    "хліб": "bread",
    "молоко": "milk",
    "м'ясо": "meat",
    "риба": "fish",
    "сир": "cheese",
    "яйце": "egg",
    "фрукти": "fruits",
    "овочі": "vegetables",
    "цукор": "sugar",
    "сіль": "salt",
    "картопля": "potato",
    "морква": "carrot",
    "помідор": "tomato",
    "огірок": "cucumber",
    "яблуко": "apple",
    "банан": "banana",
    "апельсин": "orange",
    "виноград": "grapes",
    "кава": "coffee",
    "чай": "tea",

    # Час та пори року (Time and Seasons)
    "рік": "year",
    "місяць": "month",
    "тиждень": "week",
    "день": "day",
    "година": "hour",
    "хвилина": "minute",
    "секунда": "second",
    "зима": "winter",
    "весна": "spring",
    "літо": "summer",
    "осінь": "autumn",
    "ранок": "morning",
    "день": "day",
    "ніч": "night",
    "вечір": "evening"
}
