class dir:
    def directory(self):
        ukrainian_to_english = {
            # Природа (Nature)
            "Сонце": "Sun",
            "Місяць": "Moon",
            "Зірка": "Star",
            "Небо": "Sky",
            "Вода": "Water",
            "Земля": "Earth",
            "Дерево": "Tree",
            "Ліс": "Forest",
            "Річка": "River",
            "Озеро": "Lake",
            "Гора": "Mountain",
            "Квітка": "Flower",
            "Трава": "Grass",
            "Пісок": "Sand",
            "Океан": "Ocean",
            "Хмара": "Cloud",
            "Сніг": "Snow",
            "Дощ": "Rain",
            "Вітер": "Wind",
            "Пташка": "Bird",

            # Людина (Human)
            "Чоловік": "Man",
            "Жінка": "Woman",
            "Дитина": "Child",
            "Око": "Eye",
            "Вухо": "Ear",
            "Рука": "Hand",
            "Нога": "Leg",
            "Голова": "Head",
            "Серце": "Heart",
            "Мозок": "Brain",
            "Шкіра": "Skin",
            "Кров": "Blood",
            "Кістка": "Bone",
            "Зуб": "Tooth",
            "Волосся": "Hair",
            "Обличчя": "Face",
            "Посмішка": "Smile",
            "Голос": "Voice",
            "Тіло": "Body",
            "Душа": "Soul",

            # Емоції (Emotions)
            "Радість": "Joy",
            "Смуток": "Sadness",
            "Гнів": "Anger",
            "Страх": "Fear",
            "Любов": "Love",
            "Ненависть": "Hatred",
            "Подив": "Surprise",
            "Сором": "Shame",
            "Гордість": "Pride",

                # Професії (Professions)
            "Лікар": "Doctor",
            "Вчитель": "Teacher",
            "Інженер": "Engineer",
            "Кухар": "Cook",
            "Пілот": "Pilot",
            "Водій": "Driver",
            "Музикант": "Musician",
            "Поліцейський": "Policeman",
            "Фермер": "Farmer",
            "Програміст": "Programmer",
            "Механік": "Mechanic",
            "Адвокат": "Lawyer",
            "Архітектор": "Architect",
            "Перукар": "Hairdresser",
            "Журналіст": "Journalist",
            "Художник": "Artist",
            "Фотограф": "Photographer",
            "Офіціант": "Waiter",
            "Бухгалтер": "Accountant",
            "Секретар": "Secretary",

            # Побутові предмети (Household Items)
            "Стіл": "Table",
            "Стілець": "Chair",
            "Диван": "Sofa",
            "Ліжко": "Bed",
            "Лампа": "Lamp",
            "Вікно": "Window",
            "Двері": "Door",
            "Холодильник": "Refrigerator",
            "Плита": "Stove",
            "Чашка": "Cup",
            "Тарілка": "Plate",
            "Ложка": "Spoon",
            "Вилка": "Fork",
            "Ніж": "Knife",
            "Годинник": "Clock",
            "Килим": "Carpet",
            "Дзеркало": "Mirror",
            "Шафа": "Wardrobe",
            "Пральна машина": "Washing machine",
            "Телевізор": "Television",

            # Їжа та напої (Food and Drinks)
            "Хліб": "Bread",
            "Молоко": "Milk",
            "М'ясо": "Meat",
            "Риба": "Fish",
            "Сир": "Cheese",
            "Яйце": "Egg",
            "Фрукти": "Fruits",
            "Овочі": "Vegetables",
            "Цукор": "Sugar",
            "Сіль": "Salt",
            "Картопля": "Potato",
            "Морква": "Carrot",
            "Помідор": "Tomato",
            "Огірок": "Cucumber",
            "Яблуко": "Apple",
            "Банан": "Banana",
            "Апельсин": "Orange",
            "Виноград": "Grapes",
            "Кава": "Coffee",
            "Чай": "Tea",

            # Час та пори року (Time and Seasons)
            "Рік": "Year",
            "Місяць": "Month",
            "Тиждень": "Week",
            "День": "Day",
            "Година": "Hour",
            "Хвилина": "Minute",
            "Секунда": "Second",
            "Зима": "Winter",
            "Весна": "Spring",
            "Літо": "Summer",
            "Осінь": "Autumn",
            "Ранок": "Morning",
            "День": "Day",
            "Ніч": "Night",
            "Вечір": "Evening"
        }
